// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Actions");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "tile"
                        }, React.createElement("div", {
                              className: "tile"
                            }, React.createElement("a", {
                                  className: "button is-fullwidth is-medium"
                                }, "Start")), React.createElement("div", {
                              className: "tile"
                            }, React.createElement("a", {
                                  className: "button is-fullwidth is-medium"
                                }, "Short Break")), React.createElement("div", {
                              className: "tile"
                            }, React.createElement("a", {
                                  className: "button is-fullwidth is-medium"
                                }, "Long Break")), React.createElement("div", {
                              className: "tile"
                            }, React.createElement("a", {
                                  className: "button is-fullwidth is-medium"
                                }, "Stop")));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
