// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("About");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "level"
                        }, React.createElement("div", {
                              className: "level-left"
                            }, React.createElement("p", {
                                  className: "level-item"
                                }, React.createElement("strong", undefined, "Tomato is Good."))), React.createElement("div", {
                              className: "level-right"
                            }, React.createElement("i", {
                                  className: "far fa-arrow-alt-circle-right"
                                }), React.createElement("strong", {
                                  className: "padding-left-icon"
                                }, React.createElement("a", {
                                      className: "level-item",
                                      href: "https://francescocirillo.com/pages/pomodoro-technique",
                                      target: "blank"
                                    }, "About Pomodoro Technique"))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
